### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by junoota0115** [junoota0115/protospace-39783#1]
[自身のProtoSpaceのURL]
(https://protospace-39783-37983.herokuapp.com/)
（本番環境

**Comment by motomuun** [comment]
@junoota0115 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
**プロトタイプ編集機能**

- [x] 正しく編集できた場合は、詳細ページへ遷移すること
トップページに遷移しますので、詳細ページへ遷移出来るように修正をお願いします。

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by junoota0115** [comment]
上記変更しましたので再送信いたします。
よろしくお願いいたします。

**Comment by shodai-ito** [comment]
@junoota0115 さん、再度ご提出いただきありがとうございます‼︎
動作の確認をしたところ、前回の指摘点について修正が確認できませんでした。
マージやデプロイ忘れの可能性もございます。
引き続き、以下、ご確認をお願い致します！
また、新たに修正いただきたい箇所もございましたので、そちらも併記させていただきます。

[修正依頼箇所]
**プロトタイプ編集機能**
- [x] **正しく編集できた場合は、詳細ページへ遷移すること**
編集に成功するとトップページに遷移してしまいます。

**プロトタイプ一覧表示機能**
- [x] **ログイン・ログアウトの状態に関わらず、一覧表示されている画像およびプロトタイプ名をクリックすると、該当するプロトタイプの詳細ページへ遷移すること**
プロトタイプ名をクリックしても詳細ページへ遷移できませんでした。

修正が完了しましたら、再度以下のProtoSpace完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by junoota0115** [comment]
ヘロクへの更新ができていませんでした。
再度ご確認をお願いいたします。

**Comment by shodai-ito** [comment]
@junoota0115 さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください。
